//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberStyle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int idusuario { get; set; }
        public Nullable<int> idrol { get; set; }
        [Required(ErrorMessage = "Ingrese sus nombres")]
        public string nombres { get; set; }
        [Required(ErrorMessage = "Ingrese sus apellidos")]
        public string apellidos { get; set; }

        [Required(ErrorMessage = "Ingrese su dni")]
        public string dni { get; set; }

        [Required(ErrorMessage = "Ingrese su correo")]
        public string correo { get; set; }

        [Required(ErrorMessage = "Ingrese su contraseña")]
        public string contrasenia { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
